OPENAI_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyAbC_gmob7ouat3p6E6cmkM-NgQ2NyUacA"
MISTRAL_API_KEY= "XhGADsPnZeAZDkDete7yBN5HRYWBZmfV"